name: Build and Test
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "~1.20.0"

      - name: Install benchstat
        run: go install golang.org/x/perf/cmd/benchstat@latest

      - name: Test
        run: go test ./...

      - name: Benchstat
        run: go test ./... -bench=. > out.txt && benchstat out.txt
