name: Code coverage
on: [push]
jobs:
    run:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Go
              uses: actions/setup-go@v2
              with:
                  go-version: "~1.23.0"

            - name: Code coverage
              run: go test -cover ./...
